services:
  - type: web
    name: firstmover
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: "" # set in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        value: "" # set in Render dashboard
      - key: X_BEARER_TOKEN
        value: "" # optional
    dockerfilePath: ./Dockerfile
